//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailSender_Pattern_MVVM.DB_Elements
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailSender
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string Hash { get; set; }
    }
}
