//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailSender_Pattern_MVVM.DB_Elements
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailSmtp
    {
        public int Id { get; set; }
        public string SmtpServer { get; set; }
        public string Port { get; set; }
    }
}
